#!/usr/bin/env python

import concert_service_utilities
import rospy

from concert_service_gazebo import GazeboRobotManager
from concert_service_turtlebot_gazebo import TurtlebotManager

if __name__ == '__main__':

    rospy.init_node('turtlebot_gazebo_manager')
    (service_name, unused_service_description, unused_service_id, unused_key) = concert_service_utilities.get_service_info()
    robots = rospy.get_param('robots', [])
    rospy.loginfo("GazeboTurtlebotManager: spawning robots : %s" % robots)

    turtlebot_manager = TurtlebotManager('/services/' + service_name + '/')
    turtlebot_gazebo_manager = GazeboRobotManager(turtlebot_manager)
    turtlebot_gazebo_manager.spawn_robots(robots)
    try:
        while not rospy.is_shutdown() and not turtlebot_gazebo_manager.is_disabled:
            rospy.sleep(0.3)
    except rospy.ROSInterruptException:
        pass
    turtlebot_gazebo_manager.shutdown()
