
: ${CONCERT_AUTO_ENABLE_SERVICES:=[admin]}
: ${CONCERT_ROSBRIDGE_ADDRESS:=localhost}
: ${CONCERT_WEBSERVER_ADDRESS:=localhost}
: ${CONCERT_NAME:='Yujinrobot'}


export CONCERT_AUTO_ENABLE_SERVICES
export CONCERT_ROSBRIDGE_ADDRESS
export CONCERT_WEBSERVER_ADDRESS
export CONCERT_NAME
export ROCON_AUTHORING_ROSBRIDGE_URL=ws://${CONCERT_ROSBRIDGE_ADDRESS}:9090
