
: ${CONCERT_AUTO_ENABLE_SERVICES:=[admin]}
: ${CONCERT_ROSBRIDGE_ADDRESS:=192.168.10.32}
: ${CONCERT_NAME:='Yujin Rnd'}

export CONCERT_AUTO_ENABLE_SERVICES
export CONCERT_ROSBRIDGE_ADDRESS
export CONCERT_NAME
