/*

 Copyright (c) 2012. Adobe Systems Incorporated.
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice,
 this list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 Neither the name of Adobe Systems Incorporated nor the names of its
 contributors may be used to endorse or promote products derived from this
 software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 POSSIBILITY OF SUCH DAMAGE.
*/
(function(b,c){function a(){}var d={version:0.1,inherit:function(a,d){var b=function(){};b.prototype=d.prototype;a.prototype=new b;a.prototype.constructor=a;a.prototype._super=d},ensureArray:function(){var a=[],d=arguments.length;d>0&&(a=d>1||!b.isArray(arguments[0])?b.makeArray(arguments):arguments[0]);return a},scopedFind:function(a,d,c,j){for(var c=" "+c+" ",i=[],a=b(a).find(d),d=a.length,j=b(j)[0],k=0;k<d;k++)for(var m=a[k],l=m;l;){if(l.className&&(" "+l.className+" ").indexOf(c)!==-1){l===j&&
i.push(m);break}l=l.parentNode}return b(i)}};b.extend(a.prototype,{bind:function(a,d,c){return b(this).bind(a,d,c)},unbind:function(a,d){return b(this).unbind(a,d)},trigger:function(a,d){var c=b.Event(a);b(this).trigger(c,d);return c}});d.EventDispatcher=a;c.WebPro=d})(jQuery,window,document);
(function(b,c){var a=1;c.ImageLoader=function(a){c.EventDispatcher.call();var f=this;this.options=b.extend({},this.defaultOptions,a);this._currentEntry=null;this._queue=[];this._isRunning=this._needsSort=!1;this._loader=new Image;this._loadFunc=function(){f._handleLoad()};this._loadErrorFunc=function(){f._handleError()};this._timeoutFunc=function(){f.trigger("wp-image-loader-timeout",this._currentEntry);f._loadNext()}};c.inherit(c.ImageLoader,c.EventDispatcher);b.extend(c.ImageLoader.prototype,{defaultOptions:{timeoutInterval:1E3},
add:function(d,f){if(d){urls=c.ensureArray(d);for(var g=0;g<urls.length;g++){var h=b.extend({reqId:a++,src:urls[g],width:0,height:0,priority:50,callback:null,data:null},f);this._queue.push(h);this._needsSort=!0;this.trigger("wp-image-loader-add",h)}this._isRunning&&!this._currentEntry&&this._loadNext()}},reprioritize:function(a,b){if(!(this._currentEntry&&this._currentEntry.src==a)){var c;for(c=0;c<this._queue.length;++c)if(this._queue[c].src==a)break;if(c!=0&&c<this._queue.length)this._queue=this._queue.splice(c,
b?this._queue.length-c:1).concat(this._queue)}},start:function(){if(!this._isRunning)this._isRunning=!0,this._loadNext(),this.trigger("wp-image-loader-start")},stop:function(){if(this._isRunning)this._currentEntry&&this._queue.unshift(this._currentEntry),this._resetLoader(),this._isRunning=!1,this.trigger("wp-image-loader-stop")},clearQueue:function(){var a=this._isRunning;this.stop();this._queue.length=0;a&&this.start()},isQueueEmpty:function(){return this._queue.length==0},_loadNext:function(){var d;
this._resetLoader();var a=this._queue;if(a.length){if(this._needsSort)d=this._queue=a.sort(function(a,d){var b=a.priority-d.priority;return b?b:a.reqId-d.reqId}),a=d,this._needsSort=!1;this._currentEntry=a=a.shift();var b=this._loader;b.onload=this._loadFunc;b.onerror=this._loadErrorFunc;b.src=a.src}},_resetLoader:function(){var a=this._loader;a.onload=null;a.onerror=null;this._currentEntry=a.src=null;if(this._timeoutTimerId)clearTimeout(this._timeoutTimerId),this._timeoutTimerId=0},_handleLoad:function(){var a=
this._loader,b=this._currentEntry;b.width=a.width;b.height=a.height;b.callback&&b.callback(b.src,b.width,b.height,b.data);this.trigger("wp-image-loader-load-success",b);this._loadNext()},_handleError:function(){this.trigger("wp-image-loader-load-error",this._currentEntry);this._loadNext()}})})(jQuery,WebPro,window,document);
(function(b,c){function a(){c.EventDispatcher.call(this);this._initialize.apply(this,arguments)}c.inherit(a,c.EventDispatcher);b.extend(a.prototype,{defaultOptions:{},_widgetName:"Widget",_initialize:function(){var a;this.plugins=[];var f=this.trigger("before-setup");f.isDefaultPrevented()||(a=this._setUp.apply(this,arguments),this.trigger("setup"));f=this.trigger("before-init-plugins");f.isDefaultPrevented()||(this._initializePlugins(a),this.trigger("init-plugins"));this.options=b.extend({},this.defaultOptions,
a);f=this.trigger("before-extract-data");f.isDefaultPrevented()||(this._extractData(),this.trigger("extract-data"));f=this.trigger("before-transform-markup");f.isDefaultPrevented()||(this._transformMarkup(),this.trigger("transform-markup"));f=this.trigger("before-attach-behavior");f.isDefaultPrevented()||(this._attachBehavior(),this.trigger("attach-behavior"));f=this.trigger("before-ready");f.isDefaultPrevented()||(this._ready(),this.trigger("ready"))},_setUp:function(a,f){this.$element=b(a);return f},
_initializePlugins:function(a){for(var a=a||{},b=((typeof a.useDefaultPlugins==="undefined"||a.useDefaultPlugins)&&this.defaultPlugins?this.defaultPlugins:[]).concat(a.plugins||[]),b=b.sort(function(a,d){a=typeof a.priority==="number"?a.priority:50;d=typeof d.priority==="number"?d.priority:50;return a-d}),c=0;c<b.length;c++){var h=b[c];h&&h.initialize&&h.initialize(this,a)}this.plugins=b},_extractData:function(){},_transformMarkup:function(){},_attachBehavior:function(){},_ready:function(){}});c.Widget=
a;c.widget=function(a,f,g){var h=g&&f||c.Widget,g=g||f||{},f=function(){h.apply(this,arguments);this._widgetName=a};c.inherit(f,h);b.extend(f.prototype,g);f.prototype.defaultOptions=b.extend({},h.prototype.defaultOptions,g.defaultOptions);var g=a.split("."),j=g.length;namespace=j>1&&g[0]||"Widget";a=g[j-1];c[namespace][a]=f}})(jQuery,WebPro,window,document);
(function(b,c){c.widget("Widget.Button",c.Widget,{defaultOptions:{hoverClass:"wp-button-hover",activeClass:"wp-button-down",disabledClass:"wp-button-disabled",disabled:!1,callback:null},_attachBehavior:function(){var a=this,d=function(f){a.mouseDown=!1;a.$element.removeClass(a.options.activeClass);!a.options.disabled&&a.options.callback&&a.options.callback.call(this,f);b(a.$element).off("mouseup",d)};this.mouseDown=!1;this.$element.on("mouseover",function(){a.options.disabled||a.$element.addClass(a.options.hoverClass+
(a.mouseDown?" "+a.options.activeClass:""))}).on("mouseleave",function(){a.$element.removeClass(a.options.hoverClass+" "+a.options.activeClass);b(a.$element).off("mouseup",d)}).on("mousedown",function(){if(!a.options.disabled)a.mouseDown=!0,a.$element.addClass(a.options.activeClass),b(a.$element).on("mouseup",d)});this.disabled(this.options.disabled)},disabled:function(a){if(typeof a==="boolean")this.options.disabled=a,this.$element[a?"addClass":"removeClass"](this.options.disabledClass);return this.options.disabled}});
b.fn.wpButton=function(a){this.each(function(){new c.Widget.Button(this,a)});return this}})(jQuery,WebPro,window,document);
(function(b,c){c.widget("Widget.RadioGroup",c.Widget,{_widgetName:"radio-group",defaultOptions:{defaultIndex:0,hoverClass:"wp-radio-hover",downClass:"wp-radio-down",disabledClass:"wp-radio-disabled",checkedClass:"wp-radio-checked",disabled:!1,toggleStateEnabled:!1},_attachBehavior:function(){var a=this;this.buttons=[];this.activeElement=null;this.activeIndex=-1;this.$element.each(function(){a.buttons.push(a._addButtonBehavior(this))});this.disabled(this.options.disabled)},_addButtonBehavior:function(a){var d=
this,b=new c.Widget.Button(a,{hoverClass:this.options.hoverClass,downClass:this.options.downClass,disabledClass:this.options.disabledClass,callback:function(c){return d._handleClick(c,b,a)}});return b},_handleClick:function(a,d,b){this.options.disabled||this.checkButton(b)},_getElementIndex:function(a){return a?b.inArray(a,this.$element.get()):-1},_getElementByIndex:function(a){return a>=0?this.$element.eq(a)[0]:null},_getElement:function(a){return typeof a==="number"?this._getElementByIndex(a):a},
checkButton:function(a){var a=this._getElement(a),d=this.activeElement,f=this.options.checkedClass;a!==d?(d&&b(d).removeClass(f),a&&b(a).addClass(f)):this.options.toggleStateEnabled&&a&&(b(a).removeClass(f),a=null);this.activeElement=a;this.activeIndex=this._getElementIndex(a)},disabled:function(a){if(typeof a==="boolean")this.disabled=a,b.each(this.buttons,function(){this.disabled(a)});return this.options.disabled}});b.fn.wpRadioGroup=function(a){new c.Widget.RadioGroup(this,a);return this}})(jQuery,
WebPro,window,document);
(function(b,c){c.widget("Widget.TabGroup",c.Widget.RadioGroup,{defaultOptions:{defaultIndex:0,hoverClass:"wp-tab-hover",downClass:"wp-tab-down",disabledClass:"wp-tab-disabled",checkedClass:"wp-tab-active",disabled:!1,toggleStateEnabled:!1},selectTab:function(a){this.checkButton(a)},checkButton:function(a){var d=this._getElement(a),b=this._getElementIndex(d),d={tab:d,tabIndex:b};this.trigger("wp-tab-before-select",d);this._super.prototype.checkButton.apply(this,arguments);this.trigger("wp-tab-select",d)}});
b.fn.wpTabGroup=function(a){new c.Widget.TabGroup(this,a);return this}})(jQuery,WebPro,window,document);
(function(b,c){c.widget("Widget.PanelGroup",c.Widget,{_widgetName:"panel-group",defaultOptions:{defaultIndex:0,panelClass:"wp-panel",activeClass:"wp-panel-active",toggleStateEnabled:!1,tabGroups:null},_setUp:function(){var a=this;this.tabGroups=[];this._tabCallback=function(d,b){a._handleTabSelect(d,b)};this.showLock=0;this.tabDriver=null;return this._super.prototype._setUp.apply(this,arguments)},_attachBehavior:function(){this.activeElement=null;this.activeIndex=-1;this.$element.addClass(this.options.panelClass);
var a=this.options.defaultIndex;typeof a==="number"&&a>=0&&this.showPanel(a);this.addTabGroup(this.options.tabGroups)},_getElementIndex:function(a){return a?b.inArray(a,this.$element.get()):-1},_getElementByIndex:function(a){return this.$element.eq(a)[0]},_getElement:function(a){return typeof a==="number"?this._getElementByIndex(a):a},showPanel:function(a){if(!this.showLock){++this.showLock;var d=this._getElement(a),f=this.activeElement,c=this.options.activeClass;if(d)if(d!==f){a={panel:d,panelIndex:this._getElementIndex(d)};
this.trigger("wp-panel-before-show",a);f&&this.hidePanel(f);b(d).addClass(c);this.activeElement=d;this.activeIndex=this._getElementIndex(d);d=this.tabGroups;for(f=0;f<d.length;f++)c=d[f],c!==this.tabDriver&&c.selectTab(this.activeIndex);this.trigger("wp-panel-show",a)}else this.options.toggleStateEnabled&&this.hidePanel(d);--this.showLock}},hidePanel:function(a){if(a=typeof a==="number"?this.$element.eq(a)[0]:a){var d={panel:a,panelIndex:this._getElementIndex(a)};this.trigger("wp-panel-before-hide",
d);b(a).removeClass(this.options.activeClass);if(a===this.activeElement)this.activeElement=null,this.activeIndex=-1;this.trigger("wp-panel-hide",d)}},_handleTabSelect:function(a,d){if(!this.showLock)this.tabDriver=a.target,this.showPanel(d.tabIndex),this.tabDriver=null},addTabGroup:function(a){if(a)for(var a=c.ensureArray(a),d=a.length,f=0;f<d;f++){var g=a[f];b.inArray(this.tabGroups,g)===-1&&(this.tabGroups.push(g),g.selectTab(this.activeIndex),g.bind("wp-tab-select",this._tabCallback))}},removeTabGroup:function(a){for(var a=
c.ensureArray(a),d=a.length,f=0;f<d;f++){var g=a[f];sets=this.tabGroups;loc=b.inArray(sets,g);loc!==-1&&sets.splice(loc,1)}}});b.fn.wpPanelGroup=function(a){new c.Widget.PanelGroup(this,a);return this}})(jQuery,WebPro,window,document);
(function(b,c){c.widget("Widget.Disclosure",c.Widget,{defaultOptions:{widgetClassName:"wp-disclosure-panels",tabClassName:"wp-disclosure-panels-tab",tabHoverClassName:"wp-disclosure-panels-tab-hover",tabDownClassName:"wp-disclosure-panels-tab-down",panelClassName:"wp-disclosure-panels-panel",tabActiveClassName:"wp-disclosure-panels-tab-active",panelActiveClassName:"wp-disclosure-panels-panel-active",defaultIndex:0,toggleStateEnabled:!1},_attachBehavior:function(){var a=this.$element[0],d=this.options.widgetClassName,
b=c.scopedFind(a,"."+this.options.tabClassName,d,a),a=c.scopedFind(a,"."+this.options.panelClassName,d,a);this.tabs=new c.Widget.TabGroup(b,{hoverClass:this.options.tabHoverClassName,downClass:this.options.tabDownClassName,checkedClass:this.options.tabActiveClassName,toggleStateEnabled:this.options.toggleStateEnabled});this.panels=new c.Widget.PanelGroup(a,{panelClass:this.options.panelClassName,activeClass:this.options.panelActiveClassName,defaultIndex:this.options.defaultIndex,toggleStateEnabled:this.options.toggleStateEnabled});
this.panels.addTabGroup(this.tabs)}});c.widget("Widget.TabbedPanels",c.Widget.Disclosure,{defaultOptions:{widgetClassName:"wp-tabbed-panels-panels",tabClassName:"wp-tabbed-panels-panels-tab",tabHoverClassName:"wp-tabbed-panels-panels-tab-hover",tabDownClassName:"wp-tabbed-panels-panels-tab-down",tabActiveClassName:"wp-tabbed-panels-panels-tab-active",panelClassName:"wp-tabbed-panels-panels-panel",panelActiveClassName:"wp-tabbed-panels-panels-panel-active",toggleStateEnabled:!1}});c.widget("Widget.Accordion",
c.Widget.Disclosure,{defaultOptions:{widgetClassName:"wp-accordion",tabClassName:"wp-accordion-tab",tabHoverClassName:"wp-accordion-tab-hover",tabDownClassName:"wp-accordion-tab-down",tabActiveClassName:"wp-accordion-tab-active",panelClassName:"wp-accordion-panel",panelActiveClassName:"wp-accordion-panel-active",toggleStateEnabled:!1}})})(jQuery,WebPro,window,document);
(function(b,c){c.Widget.Disclosure.DisplayPropertyTransitionPlugin={defaultOptions:{},initialize:function(a,d){var f=this;b.extend(d,b.extend({},f.defaultOptions,d));a.bind("attach-behavior",function(){f._attachBehavior(a)})},_attachBehavior:function(a){var a=a.panels,d=a.$element,b=a.activeIndex;a.bind("wp-panel-show",function(a,d){d.panel.style.display="block"});a.bind("wp-panel-hide",function(a,d){d.panel.style.display="none"});d.each(function(a){this.style.display=a!==b?"none":"block"})}};c.Widget.Disclosure.AccordionTransitionPlugin=
{defaultOptions:{transitionDirection:"vertical",transitionDuration:500,dispatchTransitionEvents:!0},initialize:function(a,d){var c=this;b.extend(d,b.extend({},c.defaultOptions,d));a.bind("attach-behavior",function(){c._attachBehavior(a)})},_attachBehavior:function(a){var d=this,b=a.panels,c=b.$element,h=b.activeIndex,j=a.options.transitionDirection;c.css("overflow","hidden");b.bind("wp-panel-show",function(b,c){d._showPanel(a,c)});b.bind("wp-panel-hide",function(b,c){d._hidePanel(a,c)});c.each(function(a){if(a!==
h){if(j==="vertical"||j==="both")this.style.height="0";if(j==="horizontal"||j==="both")this.style.width="0"}})},_transitionPanel:function(a,d){b("body").trigger("wp-page-height-change","undefined"===typeof a?0:d-a)},_showPanel:function(a,d){var c=a.options,g=c.transitionDirection,h=b(d.panel),j={},i=c.dispatchTransitionEvents,k=this,m,l=function(a){k._transitionPanel(m,a);m=a};if(g==="vertical"||g==="both")j.height=h[0].scrollHeight+"px";if(g==="horizontal"||g==="both")j.width=h[0].scrollWidth+"px";
h.stop(!0,!0).animate(j,{duration:c.transitionDuration,step:i?l:null,complete:function(){var a={};if(g==="vertical"||g==="both")a.height="auto";if(g==="horizontal"||g==="both")a.width="auto";h.css(a)}})},_hidePanel:function(a,d){var c=a.options,g=c.transitionDirection,h=b(d.panel),j={},i=c.dispatchTransitionEvents,k=this,m,l=function(a){k._transitionPanel(m,a);m=a};if(g==="vertical"||g==="both")j.height="0";if(g==="horizontal"||g==="both")j.width="0";h.stop(!0,!0).animate(j,{duration:c.transitionDuration,
step:i?l:null})}}})(jQuery,WebPro,window,document);
(function(b,c){c.widget("Widget.SlideShowBase",c.Widget,{_widgetName:"slideshow-base",defaultOptions:{displayInterval:6E3,autoPlay:!1},_setUp:function(){var a=this;this._ssTimer=0;this._ssTimerTriggered=!1;this._ssTimerCallback=function(){a._ssTimerTriggered=!0;a.next();a._ssTimerTriggered=!1};return c.Widget.prototype._setUp.apply(this,arguments)},_ready:function(){this.options.autoPlay&&this.play()},play:function(){e=this.trigger("wp-slideshow-before-play");e.isDefaultPrevented()||(this._startTimer(!1),
this.trigger("wp-slideshow-play"))},stop:function(){e=this.trigger("wp-slideshow-before-stop");e.isDefaultPrevented()||(this._stopTimer(),this.trigger("wp-slideshow-stop"))},isPlaying:function(){return this._ssTimer!==0},_startTimer:function(a){this._stopTimer();var d=this.options.displayInterval;a&&(d+=this.options.transitionDuration);this._ssTimer=setTimeout(this._ssTimerCallback,d)},_stopTimer:function(){this._ssTimer&&clearTimeout(this._ssTimer);this._ssTimer=0},_executeCall:function(a,d){e=this.trigger("wp-slideshow-before-"+
a);e.isDefaultPrevented()||(this["_"+a].apply(this,d)&&this.stop(),this.isPlaying()&&this._startTimer(!0),this.trigger("wp-slideshow-"+a))},first:function(){return this._executeCall("first",arguments)},last:function(){return this._executeCall("last",arguments)},previous:function(){return this._executeCall("previous",arguments)},next:function(){return this._executeCall("next",arguments)},goTo:function(){return this._executeCall("goTo",arguments)},_first:function(){},_last:function(){},_previous:function(){},
_next:function(){},_goTo:function(){}})})(jQuery,WebPro,window,document);
(function(b,c){c.widget("Widget.ContentSlideShow",c.Widget.SlideShowBase,{_widgetName:"content-slideshow",defaultOptions:{slideshowClassName:"wp-slideshow",clipClassName:"wp-slideshow-clip",viewClassName:"wp-slideshow-view",slideClassName:"wp-slideshow-slide",slideLinkClassName:"wp-slideshow-slide-link",firstBtnClassName:"wp-slideshow-first-btn",lastBtnClassName:"wp-slideshow-last-btn",prevBtnClassName:"wp-slideshow-prev-btn",nextBtnClassName:"wp-slideshow-next-btn",playBtnClassName:"wp-slideshow-play-btn",
stopBtnClassName:"wp-slideshow-stop-btn",playingClassName:"wp-slideshow-playing"},_findWidgetElements:function(a){var d=this.$element[0];return c.scopedFind(d,a,this.options.slideshowClassName,d)},_attachBtnHandler:function(a,d){var b=this;this["$"+d+"Btn"]=this._findWidgetElements("."+a).bind("click",function(a){b[d]();a.preventDefault()})},_reprioritizeImageLoadingIfRequired:function(a){!this._isLoaded(a)&&this._cssilLoader&&!this._cssilLoader.isQueueEmpty()&&this._cssilLoader.reprioritize(b(this.slides.$element[a]).find("img").data("src"),
this.isPlaying())},_attachBehavior:function(){var a=this,b=this.options;this._super.prototype._attachBehavior.call(this);this._panelShowCallback=function(){a._ssTimerTriggered||a.isPlaying()&&a._startTimer(!1)};this.$element.addClass(b.slideshowClassName);var f=this._findWidgetElements("."+b.slideClassName),g=this._findWidgetElements("."+b.slideLinkClassName);this.slides=new c.Widget.PanelGroup(f,{defaultIndex:b.defaultIndex||0});this.slides.bind("wp-panel-show",this._panelShowCallback);this.tabs=
null;if(g.length)this.tabs=new c.Widget.TabGroup(g,{defaultIndex:b.defaultIndex||0}),this.slides.addTabGroup(this.tabs);this.slides.bind("wp-panel-before-show",function(b,d){a._reprioritizeImageLoadingIfRequired(d.panelIndex)});this._attachBtnHandler(b.firstBtnClassName,"first");this._attachBtnHandler(b.lastBtnClassName,"last");this._attachBtnHandler(b.prevBtnClassName,"previous");this._attachBtnHandler(b.nextBtnClassName,"next");this._attachBtnHandler(b.playBtnClassName,"play");this._attachBtnHandler(b.stopBtnClassName,
"stop");this.bind("wp-slideshow-play",function(){this.$element.addClass(b.playingClassName)});this.bind("wp-slideshow-stop",function(){this.$element.removeClass(b.playingClassName)})},_first:function(){this.slides.showPanel(0)},_last:function(){var a=this.slides;a.showPanel(a.$element.length-1)},_previous:function(){var a=this.slides,b=a.activeIndex;a.showPanel((b<1?a.$element.length:b)-1)},_next:function(){var a=this.slides,b=a.activeIndex,c=(b+1)%a.$element.length;(!this.isPlaying()||this._isLoaded(b)&&
this._isLoaded(c))&&a.showPanel(c)},_goTo:function(){this.slides.showPanel.apply(this.slides,arguments)},_isLoaded:function(a){if(this._csspIsImageSlideShow&&(a=b(this.slides.$element[a]).find("img"),a.length>0&&(a.hasClass(this.options.imageIncludeClassName)||!a[0].complete)))return!1;return!0}})})(jQuery,WebPro,window,document);
(function(b,c){c.Widget.ContentSlideShow.fadingTransitionPlugin={defaultOptions:{transitionDuration:500},initialize:function(a,d){var c=this;b.extend(d,b.extend({},c.defaultOptions,d));a.bind("attach-behavior",function(){c.attachBehavior(a)})},attachBehavior:function(a){var d=this,c=a.slides,g=c.$element,h=c.activeIndex;c.bind("wp-panel-show",function(b,c){d.handleShowSlide(a,c)}).bind("wp-panel-hide",function(b,c){d.handleHideSlide(a,c)});for(c=0;c<g.length;c++)if(c!==h)g[c].style.display="none";
if(Muse.Browser.Features.Touch&&Muse.Browser.Features.Touch.Start=="touchstart"&&a.options.enableSwipe===!0){var j=a.options.transitionDuration;a._ftpSwipeNoInterrupt=!1;g.each(function(){var c=b(this);c.data("opacity",c.css("opacity"));c.swipe({triggerOnTouchEnd:!0,allowPageScroll:"vertical",threshold:75,swipeStatus:function(b,c,f,h){a.stop();if(c=="move"&&(f=="left"||f=="right"))d._scrollTo(a,-1,h*(f=="left"?1:-1),0);else if(c=="cancel")d._scrollTo(a,a.slides.activeIndex,0,j);else if(c=="end"&&
(f=="left"||f=="right")){var b=a.slides.activeIndex,i;f=="right"?i=b-1<0?g.length-1:b-1:f=="left"&&(i=b+1>g.length-1?0:b+1);d._scrollTo(a,i,0,j)}}})})}},handleShowSlide:function(a,d){var c=b(d.panel),g=!1,h=function(){g||(g=!0,c.show().css("opacity",""))},j=setTimeout(h,a.options.transitionDuration+10);c.stop(!1,!0).fadeIn(a.options.transitionDuration,function(){clearTimeout(j);h()})},handleHideSlide:function(a,d){var c=b(d.panel),g=!1,h=function(){g||(g=!0,c.hide().css("opacity",""))},j=setTimeout(h,
a.options.transitionDuration+10);c.stop(!1,!0).fadeOut(a.options.transitionDuration,function(){clearTimeout(j);h()})},_scrollTo:function(a,d,c,g){if(!a._ftpSwipeNoInterrupt){var h=a.slides.$element,j=a.slides.activeIndex,i=d==-1;d==-1&&(d=c<0?j-1<0?h.length-1:j-1:j+1>h.length-1?0:j+1);var k=b(h[j]),m=b(h[d]);if(!i&&c==0||j==d){a._ftpSwipeNoInterrupt=!0;var l=0,n=!1,o=function(){if(!n&&(n=!0,m.show().css("opacity",""),d!=j&&a.slides.showPanel(d),++l==h.length))a._ftpSwipeNoInterrupt=!1};if(m.css("opacity")!=
m.data("opacity")){var q=setTimeout(o,g+10);m.stop(!1,!0).animate({opacity:m.data("opacity")},g,function(){clearTimeout(q);o()})}else o();h.each(function(c){var f=b(this),i=!1,j=function(){if(!i&&(i=!0,f.hide().css("opacity",""),++l==h.length))a._ftpSwipeNoInterrupt=!1},k;c!=d&&(f.css("display")!="none"&&f.css("opacity")!=0?(k=setTimeout(j,g+10),f.stop(!1,!0).animate({opacity:0},g,function(){clearTimeout(k);j()})):j())})}else c=Math.abs(c),i=k.width(),c>i&&(c=i),c=m.data("opacity")*(c/i),i=k.data("opacity")*
(1-c),k.stop(!1,!0).animate({opacity:i},g),m.stop(!1,!0).show().animate({opacity:c},g)}}};c.Widget.ContentSlideShow.filmstripTransitionPlugin={defaultOptions:{transitionDuration:500,transitionStyle:"horizontal"},initialize:function(a,d){var c=this;b.extend(d,b.extend({},c.defaultOptions,d));a.bind("attach-behavior",function(){c.attachBehavior(a)})},attachBehavior:function(a){var b=this,c=a.options,g=c.transitionStyle==="horizontal",h=a.slides,j=h.$element,i=a._findWidgetElements("."+c.clipClassName),
c=a._findWidgetElements("."+c.viewClassName),k=i.width(),m=i.height(),l=g?k:m,n=0,o={top:"0",left:"0"};i.css("position")!=="absolute"&&i.css("position","relative");c.css("position")!=="absolute"&&(o.position="relative");a._fstp$Clip=i;a._fstp$View=c;a._fstpStyleProp=g?"left":"top";a._fstpStylePropZero=g?"top":"left";h.bind("wp-panel-show",function(c,f){b._goToSlide(a,f.panel)});a._fstpRequestType=null;a.bind("wp-slideshow-before-previous wp-slideshow-before-next",function(b){a._fstpRequestType=b.type.replace(/.*-/,
"");a._fstpOldActiveIndex=a.slides.activeIndex}).bind("wp-slideshow-previous wp-slideshow-next",function(){a._fstpRequestType=null;a._fstpOldActiveIndex=-1});for(var i=a._fstpStyleProp,q=a._fstpStylePropZero,p=0;p<j.length;p++){var s=j[p].style;s[q]="0";s[i]=n+"px";s.margin="0";s.position="absolute";n+=l}o[g?"width":"height"]=n+"px";o[g?"height":"width"]=(g?m:k)+"px";h.activeElement||(o[i]=(g?k:m)+"px",o[q]="0");o.overflow="visible";c.css(o);b._goToSlide(a,h.activeElement)},_goToSlide:function(a,
d){if(a){var c=b(d),g=a._fstp$View,h=a._fstpStyleProp,j=h==="left"?"offsetLeft":"offsetTop",i=h==="left"?"offsetWidth":"offsetHeight",k=d?-d[j]:a._fstp$Clip[0][i],m={};m[h]=k+"px";var l=a._fstpRequestType,n=a._fstpOldActiveIndex;if(l&&n!==-1){var o=a.slides.activeIndex,q=a.slides.$element.length-1;if(o!==n){var p=0;l==="previous"&&n===0&&o===q?p=-d[i]:l==="next"&&n===q&&o===0&&(l=a.slides.$element[n],p=l[j]+l[i]);p&&(m[h]=-p+"px",c.css(h,p+"px"))}}g.stop(!1,!0).animate(m,a.options.transitionDuration,
function(){p&&(c.css(h,-k+"px"),g.css(h,k+"px"))})}}};c.Widget.ContentSlideShow.swipeTransitionPlugin={defaultOptions:{transitionDuration:500,transitionStyle:"horizontal"},initialize:function(a,d){var c=this;b.extend(d,b.extend({},c.defaultOptions,d));a.bind("attach-behavior",function(){c.attachBehavior(a)})},attachBehavior:function(a){var b=this,c=a.options,g=c.transitionStyle==="horizontal",h=a.slides,j=h.$element,i=a._findWidgetElements("."+c.clipClassName),k=a._findWidgetElements("."+c.viewClassName),
m=i.width(),l=i.height(),n=g?m:l,m=0,l={top:"0",left:"0"};i.css("position")!=="absolute"&&i.css("position","relative");k.css("position")!=="absolute"&&(l.position="relative");a._fstp$Clip=i;a._fstp$View=k;a._fstpStyleProp=g?"left":"top";a._fstpStylePropZero=g?"top":"left";h.bind("wp-panel-show",function(){var g=a.slides.activeIndex*n,h=a.options.transitionDuration;g==0&&a.slides.activeIndex==0&&!c.shuffle&&a.isPlaying()&&(h=0);b._scrollTo(a,g,h)});a._fstpRequestType=null;a.bind("wp-slideshow-before-previous wp-slideshow-before-next",
function(b){a._fstpRequestType=b.type.replace(/.*-/,"");a._fstpOldActiveIndex=a.slides.activeIndex}).bind("wp-slideshow-previous wp-slideshow-next",function(){a._fstpRequestType=null;a._fstpOldActiveIndex=-1});for(var i=a._fstpStyleProp,o=a._fstpStylePropZero,q=0;q<j.length;q++){var p=j[q].style;p[o]="0";p[i]=m+"px";p.margin="0";p.position="absolute";m+=n}l[g?"width":"height"]=m+"px";l[g?"height":"width"]=n+"px";l.overflow="visible";k.css(l);var s=a.options.transitionDuration;k.swipe({triggerOnTouchEnd:!0,
allowPageScroll:g?"vertical":"horizontal",threshold:75,swipeStatus:function(c,f,h,i){a.stop();if(f=="move"&&(g&&(h=="left"||h=="right")||!g&&(h=="up"||h=="down")))h=n*a.slides.activeIndex+i*(h=="left"||h=="up"?1:-1),b._scrollTo(a,h,0);else if(f=="cancel")h=n*a.slides.activeIndex,b._scrollTo(a,h,s);else if(f=="end"){c=-1;if(g&&h=="right"||!g&&h=="down")c=Math.max(a.slides.activeIndex-1,0);else if(g&&h=="left"||!g&&h=="up")c=Math.min(a.slides.activeIndex+1,k.children().length-1);c!=-1&&(h=n*c,b._scrollTo(a,
h,s),c!=a.slides.activeIndex&&a.slides.showPanel(c))}}});b._scrollTo(a,h.activeElement?h.activeIndex*n:1*n,0)},_scrollTo:function(a,b,c){var d;var g=Muse.Browser.Features.checkCSSFeature("transition-duration"),h=Muse.Browser.Features.checkCSSFeature("transform");if(!(g===!1||h===!1)){var j=a._fstp$View.get(0);j.style[(g===!0?"":"-"+g.toLowerCase()+"-")+"transition-duration"]=(c/1E3).toFixed(1)+"s";b=-b;d=(c=a.options.transitionStyle==="horizontal")?b:0,a=d;b=c?0:b;h=(h===!0?"":"-"+h.toLowerCase()+
"-")+"transform";c="translate3d("+a+"px, "+b+"px, 0px)";g=j.style[h];j.style[h]=c;j.style[h]===g&&g!==c&&(j.style[h]="translate("+a+"px, "+b+"px)")}}};c.Widget.ContentSlideShow.slideImageIncludePlugin={defaultOptions:{imageIncludeClassName:"wp-slideshow-slide-image-include",slideLoadingClassName:"wp-slideshow-slide-loading"},initialize:function(a,d){var f=this;b.extend(d,b.extend({},f.defaultOptions,d));a._cssilLoader=new c.ImageLoader;a.bind("attach-behavior",function(){f._attachBehavior(a)})},_attachBehavior:function(a){for(var b=
this,c=a._cssilLoader,g=a._findWidgetElements("."+a.options.slideClassName),h=g.length,j="."+a.options.imageIncludeClassName,i=a.options.slideLoadingClassName,k=function(c,f,g,h){b._handleImageLoad(a,c,f,g,h)},m=0;m<h;m++){var l=g.eq(a._shuffleArray?a._shuffleArray[m]:m),n=l.find(j);if(ele=n[0]){var o=n.data("src")||ele.href;if(o)n={id:ele.id||"",classAttr:ele.className||"",alt:ele.alt,width:n.data("width"),height:n.data("height"),$ele:n,$slide:l},ele.style.visibility="hidden",c.add(o,{callback:k,
data:n}),l.addClass(i)}}a._cssilLoader.start()},_handleImageLoad:function(a,d,c,g,h){d=b('<img id="'+(h.id||"")+'" class="'+h.classAttr+'" alt="'+h.alt+'" src="'+d+'" width="'+(h.width||c)+'" height="'+(h.height||g)+'">');d.removeClass(a.options.imageIncludeClassName);h.$ele.replaceWith(d);h.$slide.removeClass(a.options.slideLoadingClassName);a.isPlaying()&&a.slides.$element[a.slides.activeIndex]==h.$slide[0]&&a._startTimer(!1)}};c.Widget.ContentSlideShow.shufflePlayPlugin={defaultOptions:{randomDefaultIndex:!0},
initialize:function(a,d){var c=this;b.extend(d,b.extend({},c.defaultOptions,d));a._shuffleArray=[];a._shuffleNextDict={};a._realNext=a._next;a._next=function(){c._handleNext(a)};a._shufflePlayCount=0;a.bind("before-attach-behavior",function(){c._reshuffle(a);if(d.randomDefaultIndex&&typeof d.defaultIndex==="undefined")a.options.defaultIndex=a._shuffleArray[0]})},_fisherYatesArrayShuffle:function(a){if(a&&a.length)for(var b=a.length;--b;){var c=Math.floor(Math.random()*(b+1)),g=a[c];a[c]=a[b];a[b]=
g}},_reshuffle:function(a){var b=a._shuffleArray,c={},g=a.slides?a.slides.$element.length:a._findWidgetElements("."+a.options.slideClassName).length;if(b.length!==g)for(var h=b.length=0;h<g;h++)b[h]=h;this._fisherYatesArrayShuffle(b);for(h=0;h<g;h++)c[b[h]]=b[(h+1)%g];a._shuffleNextDict=c;a._shufflePlayCount=0},_handleNext:function(a){if(a.isPlaying()){var b=a.slides.activeIndex,c=a._shuffleNextDict[b]||0;a._isLoaded(b)&&a._isLoaded(c)&&(a._goTo(c),++a._shufflePlayCount>=a.slides.$element.length&&
this._reshuffle(a))}else a._realNext()}}})(jQuery,WebPro,window,document);
(function(b,c){c.widget("Widget.Form",c.Widget,{_widgetName:"form",defaultOptions:{validationEvent:"blur",errorStateSensitivity:"low",ajaxSubmit:!0,fieldWrapperClass:"field",formErrorClass:"form-error",formSubmittedClass:"form-submitted",formDeliveredClass:"form-delivered",focusClass:"focus",notEmptyClass:"not-empty",emptyClass:"empty",validClass:"valid",invalidClass:"invalid",requiredClass:"required"},validationTypes:{"always-valid":/.*/,email:/^[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/i,
alpha:/^[A-z\s]+$/,numeric:/^[0-9]+$/,phone:/^([0-9])?(\s)?(\([0-9]{3}\)|[0-9]{3}(\-)?)(\s)?[0-9]{3}(\s|\-)?[0-9]{4}(\s|\sext|\sx)?(\s)?[0-9]*$/,captcha:function(a){return a.data("captchaValid")},time:function(a){var a=a.find("input, textarea"),b=a.val().replace(/[^0-9:APM]/g,"");if(b.indexOf(":")!=-1&&b.match(/:/).length==1){var c=b.split(":"),g=parseInt(c[0]),c=parseInt(c[1]);if(g<0||g>24)return!0;if(c<0||c>59)return!0}else return!1;a.val(b);return!0}},_transformMarkup:function(){var a=this;a.hasCAPTCHA=
!1;this.$element.find("."+this.options.fieldWrapperClass).each(function(){var c=b(this);if(c.attr("data-type")=="captcha")a.hasCAPTCHA=!0,c.find('input[name="CaptchaV2"]').remove(),c.find('input[name="muse_CaptchaV2"]').attr("name","CaptchaV2")})},_extractData:function(){this.event=this.options.validationEvent;this.errorSensitivity=this.options.errorStateSensitivity;this.classNames={focus:this.options.focusClass,blur:this.options.emptyClass,keydown:this.options.notEmptyClass}},_attachBehavior:function(){var a=
this;this.$element.find("input, textarea").each(function(){var c=b(this);c.val()!=""&&c.removeClass(a.options.emptyClass)});this.$element.find("."+this.options.fieldWrapperClass).each(function(){var c=b(this);c.attr("data-type")=="captcha"&&(c.data("captchaValid",!1),c.find('input[name="CaptchaV2"]').keyup(function(){var f=b(this).val(),g=c.find('input[name="CaptchaHV2"]').val();a._validateCaptcha(g,f,function(b){c.data("captchaValid",b);c.data("error-state")&&a.errorSensitivity=="high"&&a._validate(c)})}));
c.find("input, textarea").val()!=""&&c.addClass(a.classNames.keydown)});this.$element.find("input, textarea").bind("focus blur keydown change propertychange",function(c){var f=a.classNames[c.type],g=a.classNames.focus,h=a.classNames.keydown,j=a.classNames.blur,i=b(this),k=i.closest("."+a.options.fieldWrapperClass);switch(c.type){case "focus":k.addClass(f).removeClass(j);break;case "blur":k.removeClass(g);i.val()==""&&k.addClass(f).removeClass(h);break;case "keydown":k.addClass(f).removeClass(j);break;
case "change":case "propertychange":i.val()!=""?k.addClass(h).removeClass(j):k.addClass(j).removeClass(h)}});switch(this.event){case "blur":case "keyup":this.$element.find("."+this.options.fieldWrapperClass+" input, ."+this.options.fieldWrapperClass+" textarea").bind(this.event,function(){a._validate(b(this).closest("."+a.options.fieldWrapperClass))});case "submit":this.$element.submit(function(c){var f=!0,g=a.$element.find("."+a.options.fieldWrapperClass).length-1;a.$element.find("."+a.options.fieldWrapperClass).each(function(h){if((f=
a._validate(b(this))?f:!1)&&h==g&&a.options.ajaxSubmit)c.preventDefault(),a._submitForm();f||c.preventDefault()})})}},_validateCaptcha:function(a,c,f){c.length!=6?f(!1):b.get("/ValidateCaptcha.ashx",{key:a,answer:c},function(a){f(a=="true")})},_submitForm:function(){var a=this,c=this.options.formSubmittedClass,f=this.options.formDeliveredClass,g=this.options.formErrorClass,h=c+" "+f+" "+g,j=this.$element.find("input[type=submit], button");b.ajax({url:this.$element.attr("action"),type:"post",data:this.$element.serialize(),
beforeSend:function(){a.$element.removeClass(h);a.$element.addClass(c);a.$element.find("."+a.options.fieldWrapperClass).removeClass(a.options.focusClass);j.attr("disabled","disabled")},complete:function(h){h&&h.responseText&&h.responseText.indexOf('"success": true')>0?(a.$element.addClass(f).removeClass(c),a.$element.find("input:not([type=submit]), textarea").each(function(){var c=b(this);c.val("");a.hasCAPTCHA&&c.attr("disabled","disabled")})):a.$element.addClass(g).removeClass(c);a.hasCAPTCHA||
j.removeAttr("disabled")}})},_validate:function(a){var b=a.attr("data-type")||"always-valid",c=a.find("input, textarea"),g=this.validationTypes[b],b=a.attr("data-required")==="true",h=c.val()=="",c=g instanceof RegExp?Boolean(c.val().match(g)):g(a);if(b&&h)return this._switchState("required",a);if(!c)return this._switchState("invalid",a);return this._switchState("valid",a)},_switchState:function(a,b){function c(){i._validate(b)}var g=this.options.validClass,h=this.options.invalidClass,j=this.options.requiredClass;
b.removeClass(g+" "+h+" "+j);if(a=="required"||a=="invalid"){a=="invalid"?b.addClass(h):b.addClass(j);if(this.errorSensitivity!="low"){var i=this,g=this.errorSensitivity=="high"?"keyup":"blur";b.data("error-state")||(b.data("error-state",!0),b.find("input, textarea").bind(g,c))}return!1}b.data("error-state")&&(this.errorSensitivity=="high"?this.event!="keyup"&&b.data("error-state",!1).find("input, textarea").unbind("keyup",c):this.errorSensitivity=="medium"&&this.event!="blur"&&b.data("error-state",
!1).find("input, textarea").unbind("blur",c));b.addClass(g);return!0}});b.fn.wpForm=function(a){new c.Widget.Form(this,a);return this}})(jQuery,WebPro,window,document);
